export const SEND_NUMBER = 'SEND_NUMBER'
export const SET_NUMBER = 'SET_NUMBER'
export const CLEAR_NUMBER = 'CLEAR_NUMBER'
export const RESET_GAME = 'RESET_GAME'
export const NUMBER_QUESTIONS = 20
export const ADD_FEEDBACK = 'ADD_FEEDBACK'
export const CLEAR_FEEDBACKS = 'CLEAR_FEEDBACKS'
